# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create(:name => 'Brett Eastwood', :email => 'brett@propellernet.co.uk', :team => 'Retail', :speciality => 'PPC', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Carla Butterfield', :email => 'carla@propellernet.co.uk', :team => 'Retail', :speciality => 'Client Services', :normal_hours => 80, :admin => false, :line_manager => 2)
User.create(:name => 'Colin Differ', :email => 'colin@propellernet.co.uk', :team => 'Travel', :speciality => 'Tech SEO', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Dan Goodwin', :email => 'dan@propellernet.co.uk', :team => 'None', :speciality => 'Product', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Ed Lamb', :email => 'ed@propellernet.co.uk', :team => 'Retail', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Eshe Brown', :email => 'eshe@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Gary Preston', :email => 'gary@propellernet.co.uk', :team => 'None', :speciality => 'Strategy', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Gemma Cocker', :email => 'gemma@propellernet.co.uk', :team => 'Travel', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Hannah Foster', :email => 'hannahf@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Hannah Nice', :email => 'hannahn@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Helen McClane', :email => 'helen@propellernet.co.uk', :team => 'Travel', :speciality => 'Client Services', :normal_hours => 60, :admin => false, :line_manager => 2)
User.create(:name => 'Isa Lavahun', :email => 'isa@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Jake Reeves', :email => 'jacob@propellernet.co.uk', :team => 'Retail', :speciality => 'PPC', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'James Campbell', :email => 'james.campbell@propellernet.co.uk', :team => 'Travel', :speciality => 'PPC', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'James Miller', :email => 'jamesm@propellernet.co.uk', :team => 'Retail', :speciality => 'Tech SEO', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'James Sandford', :email => 'james@propellernet.co.uk', :team => 'Travel', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Jim Kirby', :email => 'jimk@propellernet.co.uk', :team => 'Retail', :speciality => 'PPC', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Kim Button', :email => 'kim@propellernet.co.uk', :team => 'Travel', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Laura Wilkins', :email => 'wilky@propellernet.co.uk', :team => 'Travel', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Laura Joint', :email => 'laura@propellernet.co.uk', :team => 'Travel', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Liam Phillips', :email => 'liam@propellernet.co.uk', :team => 'Travel', :speciality => 'Tech SEO', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Louise Greeves', :email => 'louise@propellernet.co.uk', :team => 'Retail', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Mark Slade', :email => 'marks@propellernet.co.uk', :team => 'Retail', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Megan Hart', :email => 'megan@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Kelly Jones', :email => 'kelly@propellernet.co.uk', :team => 'Retail', :speciality => 'PPC', :normal_hours => 42, :admin => false, :line_manager => 2)
User.create(:name => 'Rachel Krish', :email => 'rachel@propellernet.co.uk', :team => 'None', :speciality => 'Client Services', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Rik Turner', :email => 'rik@propellernet.co.uk', :team => 'Retail', :speciality => 'Tech SEO', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Rob Green', :email => 'rob@propellernet.co.uk', :team => 'Travel', :speciality => 'PPC', :normal_hours => 100, :admin => 'true', :line_manager => 2)
User.create(:name => 'Robin Fry', :email => 'robin@propellernet.co.uk', :team => 'Retail', :speciality => 'Tech SEO', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Simon Mustoe', :email => 'simon@propellernet.co.uk', :team => 'None', :speciality => 'Strategy', :normal_hours => 40, :admin => false, :line_manager => 2)
User.create(:name => 'Simone Stevens', :email => 'simone@propellernet.co.uk', :team => 'Retail', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Sophie Coley', :email => 'sophie@propellernet.co.uk', :team => 'None', :speciality => 'Strategy', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Sophie Tanner', :email => 'sophiet@propellernet.co.uk', :team => 'Travel', :speciality => 'Cultivate', :normal_hours => 80, :admin => false, :line_manager => 2)
User.create(:name => 'Stefan Teska', :email => 'stefant@propellernet.co.uk', :team => 'None', :speciality => 'Product', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Stella Bayles', :email => 'stella@propellernet.co.uk', :team => 'None', :speciality => 'Strategy', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Stephanie Sheehan', :email => 'stephanie@propellernet.co.uk', :team => 'Travel', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)
User.create(:name => 'Stephen Baker', :email => 'stephen@propellernet.co.uk', :team => 'Travel', :speciality => 'Cultivate', :normal_hours => 100, :admin => false, :line_manager => 2)

Client.create(:name => 'Atterley Road', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'BIMM', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Betfair', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Alamy', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Contiki', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'CSMA', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'CV Villas', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Endsleigh', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Forest Holidays', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Hibu', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Kiddicare', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'LK Bennett', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'London City Airport', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Marks & Spencers', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Maximise', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'McArthurGlen', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'MF Group', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Long Tall Sally', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Purple Parking', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Smartstream', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Sportsshoes', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Black Tomato', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Travel Zoo', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Telegraph', :email => 'example@propellernet.co.uk', :team => 'Travel', :account_director => 2)
Client.create(:name => 'Waitrose Direct', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
Client.create(:name => 'Waitrose.com', :email => 'example@propellernet.co.uk', :team => 'Retail', :account_director => 2)
